apiVersion: v1
kind: Service
metadata:
  name: {{ include "raven-miner.fullname" . }}
  labels:
    {{- include "raven-miner.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dashboard
      protocol: TCP
      name: dashboard
  selector:
    {{- include "raven-miner.selectorLabels" . | nindent 4 }}
